apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  mode: daemonset
  hostNetwork: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    exporters:
      logging:
      otlphttp:
        endpoint: TEMPO_SERIVCE_NAME:4317

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging,otlphttp]